k8s fiel directory

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -99,14 +99,23 @@ jobs:
     - name: "1. Checkout de código"
       uses: actions/checkout@v4
 
-    - name: "2. Definir variables de despliegue"
+    - name: "2. Definir Tag y Servidor ACR"
       id: vars
       run: |
-        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
-          echo "K8S_OVERLAY=prod" >> $GITHUB_ENV
-        else
-          echo "K8S_OVERLAY=test" >> $GITHUB_ENV
+        # --- NUEVA VALIDACIÓN ---
+        # Falla el pipeline si el secreto está vacío
+        if [ -z "${{ secrets.ACR_NAME }}" ]; then
+          echo "::error:: El secreto 'ACR_NAME' no está configurado en el Entorno de GitHub."
+          exit 1
         fi
+        echo "Secreto 'ACR_NAME' encontrado: ${{ secrets.ACR_NAME }}"
+        # -------------------------
+
+        ACR_NAME=${{ secrets.ACR_NAME }}
+        echo "ACR_LOGIN_SERVER=$ACR_NAME.azurecr.io" >> $GITHUB_OUTPUT
+
+        IMAGE_TAG=${{ github.sha }}
+        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
 
     - name: "3. Instalar Kustomize"
       run: |
